In [1]:
from PIL import Image
import numpy as np

img = Image.open('t2p23.jpg')   # 使用 PIL 打开图片
data1 = img.getdata()   # 获取图片的数据信息 class <'ImagingCore'>
data1 = np.array(data1)   # 把这个数据通过 numpy 转换成多维度的张量
data1

array([[203, 203, 203],
       [222, 222, 222],
       [221, 221, 221],
       ...,
       [224, 224, 224],
       [228, 228, 228],
       [205, 205, 205]])

In [2]:
data1[4030,]

array([217, 217, 217])

这个本来该3维的张量变成2维
n行m列 
n:0-99

[n][m]=[ 100*n+m ]


In [3]:
data=np.zeros(100).reshape(10,10)

In [5]:
for i in range(10):
    for j in range(10):
        cnt=0
        for ii in range(10):
            for jj in range(10):
                
                a1=data1[ 1000*i+10*j+100*ii+jj,0 ]
                a2=data1[ 1000*i+10*j+100*ii+jj,1 ]
                a3=data1[ 1000*i+10*j+100*ii+jj,2 ]
                
                if( abs(a1-a2)>10 or abs(a1-a3)>10 or abs(a2-a3)>10 ):
                    cnt+=1
        if(cnt>50):
            data[i,j]=1
        else:
            data[i,j]=0


In [6]:
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0., 0.],
       [0., 1., 1., 0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
import pandas as pd
writer = pd.ExcelWriter('transform2.xlsx')
data_df = pd.DataFrame(data)   #关键1，将ndarray格式转换为DataFrame

# 更改表的索引
data_df.columns = ['1','2','3','4','5','6','7','8','9','10']  #将第一行的0,1,2,...,9变成A,B,C,...,J
data_df.index = ['1','2','3','4','5','6','7','8','9','10']
data_df.to_excel(writer,'page_1',float_format='%.5f')  #关键3，float_format 控制精度，将data_df写到hhh表格的第一页中。若多个文件，可以在page_2中写入
writer.save()  #关键4